variables:
  SG_JAVA_BUILD_VERSION: "11"
  MAVEN_OPTS: "-Dmaven.repo.local=m2repository"

image: maven:3.6-jdk-${SG_JAVA_BUILD_VERSION}

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
  - "sgbuild0/search-guard-suite-enterprise/m2repository" #path look like this because of mv we do below

before_script:
- rm -rf /var/lib/apt/lists/* && apt-get update -yqq && apt-get install -yqq apt-utils jq perl libapr1 openssl libxml2-utils curl uuid-runtime ftp gnupg2 netcat pinentry-tty expect psmisc xmlstarlet sudo > /dev/null 2>&1
- eval $(ssh-agent -s)
- echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
- mkdir -p ~/.ssh
- chmod 700 ~/.ssh
- ssh-keyscan git.floragunn.com >> ~/.ssh/known_hosts
- chmod 644 ~/.ssh/known_hosts
- mkdir -p sgbuild0/search-guard-suite-enterprise
- mv -f * sgbuild0/search-guard-suite-enterprise || true #mv search-guard-suite to be able to have search-guard-suite and search-guard-suite-enterprise on the same level -> https://gitlab.com/gitlab-org/gitlab-runner/issues/4672#note_212006686
- mv -f .git* sgbuild0/search-guard-suite-enterprise || true #dot files/directory need to be moved explicitly
# clone search-guard-suite-enterprise on the same level as search-guard-suite
- git clone git@git.floragunn.com:search-guard/search-guard-suite.git sgbuild0/search-guard-suite; cd sgbuild0/search-guard-suite; git checkout $CI_COMMIT_REF_NAME; cd ../search-guard-suite-enterprise

build_and_deploy:
  script:
  - cd ../search-guard-suite; esversion=$(xmlstarlet sel -N my=http://maven.apache.org/POM/4.0.0 -t -m my:project -m my:properties -v my:elasticsearch.version pom.xml); mvn -Drevision=b-$esversion-SNAPSHOT -DskipTests -s settings.xml clean install ; cd ../search-guard-suite-enterprise
  - mvn -Drevision=b-$esversion-SNAPSHOT -s settings.xml clean verify #run tests
  #saving unittests reports in different folder before removing them on next step
  - cp -r /builds/search-guard/search-guard-suite-enterprise/sgbuild0/search-guard-suite-enterprise/dlic-security/target/surefire-reports/ /builds/search-guard/search-guard-suite-enterprise/sgbuild0/dlic-security/ || true
  - cp -r /builds/search-guard/search-guard-suite-enterprise/sgbuild0/search-guard-suite-enterprise/dlic-signals/target/surefire-reports/ /builds/search-guard/search-guard-suite-enterprise/sgbuild0/dlic-signals/ || true
  - mvn -Drevision=b-$esversion-SNAPSHOT -DskipTests -s settings.xml clean deploy #deploy snapshot
  #- missing: veracode, coverage, srcclr, sonar, scan_veracode.sh
  retry:
    max: 2

  #saving unittests reports
  artifacts:
    when: always
    paths:
      - sgbuild0/surefire-reports/
      - sgbuild0/dlic-security/
      - sgbuild0/dlic-signals/
      - sgbuild0/search-guard-suite-enterprise/dlic-signals/
      - sgbuild0/search-guard-suite-enterprise/dlic-security/
  #only used in merge request so far, so it makes not much sense to upload them
  #artifacts:
  #  reports:
  #    junit:
  #    - target/surefire-reports/TEST-*.xml
