variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository "
  SG_JAVA_BUILD_VERSION: "11"

image: maven:3.6-jdk-${SG_JAVA_BUILD_VERSION}

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
  - .m2/repository

before_script:
- rm -rf /var/lib/apt/lists/* && apt-get update -yqq && apt-get install -yqq apt-utils jq perl libapr1 openssl libxml2-utils curl uuid-runtime ftp gnupg2 netcat pinentry-tty expect psmisc xmlstarlet sudo
- echo "VERSIONS:"
- uname -a;java -version;openssl version

stages:
- test
- deploy

verify:
  stage: test
  script:
  - ./smoketest.sh
  - if [ "$CI_COMMIT_REF_NAME" == "master" ]; then mvn --fail-at-end -U -Pcoverage verify -s settings.xml; else mvn --fail-at-end -U verify -s settings.xml; fi
  artifacts:
    reports:
      junit:
      - target/surefire-reports/TEST-*.xml
deploy:
  stage: deploy
  only:
    variables:
    - $CI_COMMIT_REF_NAME == "master"
  script:
  - mvn deploy --fail-at-end -U -Penterprise -DskipTests -s settings.xml
  #    - mvn -U --fail-at-end -s settings.xml -Pcoverage sonar:sonar -Dsonar.organization=floragunncom-github -Dsonar.login=$SONAR_LOGIN -Dsonar.host.url=https://sonarcloud.io || true
  - mvn --fail-at-end clean verify com.srcclr:srcclr-maven-plugin:scan -Penterprise -DskipTests -U -s settings.xml
#    -./dev/scan_veracode.sh
