# This file defines the authentication frontends for Kibana. 
#
# If you want to login a username/password login form, you can leave this file as it is. The authentication backends used for 
# verifying the username and password, are configured in sg_config.yml.
#
# If you want to use SAML or OIDC based authentication, you have to provide additional configuration here. You can use the configuration 
# examples below as a starting point.
# 
# NOTE: For using SAML or OIDC based authentication, you have to obtain a license.
# 
# You can use any number of authentication methods at once. Search Guard will present you a selection of all available authentication methods in the browser.
#
# If you use more than one Kibana instance, you can add additonal root entries besides the default entry. In kibana.yml you can then select the configuration
# to be used by the config option searchguard.sg_frontend_config_id

_sg_meta:
  type: "frontend_config"
  config_version: 2
    
default:
  authcz:
  - type: basic
  - type: saml
    enabled: false
    label: "SAML Login"
    idp.metadata_url: "https://your.idp.example.com/saml-metadata.xml"
    idp.entity_id: urn:saml-metadata-entity-id
    sp.entity_id: service-provider-id
    user_mapping.roles: roles
  - type: oidc
    enabled: false
    label: "OIDC Login"
    client_id: "your-oidc-client-id"
    client_secret: "your-oidc-client-secret"
    idp.openid_configuration_url: "https://your.idp.example.com/auth/realms/master/.well-known/openid-configuration"
    user_mapping.roles: roles
    